config/routes.rb
StoreV2::Application.routes.draw do
  root to: 'home#index'
  resources :products
  resources :users
  resources :sessions
  resources :product_uploads


  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, presence: true
  validates_numericality_of :price
  has_attached_file :picture, styles: { small: "100x100>", medium: "250x250>" }

  validates_attachment_content_type :picture, :content_type =>
  ["image/jpg", "image/jpeg", "image/png"]
end

app/models/product_upload.rb
class ProductUpload
  include ActiveModel::Model

  def initialize(file)
    @file = file
  end

  def parse!
    invalid_array = []
    products_attributes = SmarterCSV.process(@file.tempfile)
    products_attributes.each do |product_attributes|
      @product = Product.new(product_attributes)
      if !@product.save
        invalid_array << @product
      else
      end
    end
    invalid_array
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to sessions_path, alert: "Not authorized" if current_user.nil?
  end

  def bossthorize
    redirect_to root_path, alert: "Not authorized" if current_user.admin != true
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all
    render('index.html.erb')
  end
end

app/controllers/product_uploads_controller.rb
class ProductUploadsController < ApplicationController

  def new
  end

  def create
    @invalid_array = ProductUpload.new(params[:product_upload][:csv]).parse!
    render 'show'
  end


private

  def products_uploads_params
    params.require(:product_upload).permit(:csv, :invalid_array)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_filter :authorize, except: [:show]

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
    @product_upload = ProductUpload.new(:csv)
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if params[:product]
      @product.update(products_params)
    end
      redirect_to product_path
  end

  def create
    @product = Product.new(products_params)
    @invalid_array
    if @product.save
      flash[:notice] = "Animal Added"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to(root_path)
  end

private

  def products_params
    params.require(:product).permit(:id, :name, :price, :description, :picture)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def index

  end

  def new
  end

  def create
    user = User.find_by_name(params[:name])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash[:alert] = "Email or password is invalid"
      redirect_to :back
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :bossthorize, except: [:index]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if params[:user]
      @user.update(users_params)
    end
      redirect_to user_path
  end

  def create
    @user = User.create(users_params)
    redirect_to(root_path)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to(root_path)
  end

private

  def users_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% content_for(:title, "Home | Jungle") %>

<h1>Welcome to the Jungle</h1>

<h1>Exotic Animals</h1>

<% @products.each do |product| %>
  <%= image_tag(product.picture.url(:small)) %>
  <%= link_to "#{product.name}", product_path(product), class: "below" %>
<% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
  <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <div class="navbar navbar-default navbar-fixed-top">
    <%= link_to "Home", root_url, class: "navbar-text pull-left" %>
    <% if current_user %>
      <%= link_to "Log Out", session_path("current"), method: "delete", class: "navbar-text pull-right" %>
      <%= link_to "Users", users_path("current"), method: "get", class: "navbar-text pull-right" %>
      <%= link_to "New Product", new_product_path, method: "get", class: "navbar-text pull-left" %>
      <div class="navbar-text pull-right">
       Logged in as &nbsp; <%= link_to current_user.name, user_path(current_user), id: "white" %>
      </div>
    <% else %>
      <%= link_to "Log In", sessions_path, class: "navbar-text pull-right" %>
    <% end %>
  </div>
  <div id="main">
  <%= flash[:notice] %>
  <%= flash[:alert] %>
<%= yield %>
  </div>
</div>

</body>
</html>

app/views/product_uploads/show.html.erb
<h3>Valid Items Added to Database!</h3>

<% @invalid_array.each do |invalid| %>
  <p>This item was invalid<p>
  Name: <%= invalid.name %><br>
  Price: <%= invalid.price %><br>
  Description: <%= invalid.description %><br>
<% end %>

app/views/products/_form.html.erb
<%= form_for @product, :html => { :multipart => true } do |f| %>
  <div class='form-group'>
    <%= f.label "Product Name" %>
    <%= f.text_field :name %>
    <%= f.label "Price" %>
    <%= f.text_field :price %>
    <%= f.label "Description"%>
    <%= f.text_field :description %>
  </div>
    <%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/products/edit.html.erb
<% content_for(:title, "#{@product.name} | Edit menu") %>

<h1>Edit Menu </h1>

<%= render('layouts/errors', object: @product) %>
  <%= render('form') %>

<% if @product.picture.instance.picture_file_name.nil? %>
  <h3>Add a Photo for this animal</h3>
  <%= form_for @product do |f| %>
    <% f.label :picture %>
    <%= f.file_field :picture %>
    <%= f.submit "Submit", class: "btn btn-success margin-high" %>
  <% end %>
<% else %>
  <h3>Update Photo</h3>
  <%= form_for @product, url: product_path do |f| %>
  <% f.label :picture %>
  <%= f.file_field :picture %>
  <%= f.submit "Update", class: "btn btn-warning margin-high" %>
  <% end %>
<% end %>

app/views/products/index.html.erb
<% content_for(:title, "All Products | Jungle") %>

<h1>Exotic Animals</h1>

<ul>
  <% @products.each do |product| %>
    <li><%= link_to "#{product.name}", product_path(product) %>
    </li>
  <% end %>
</ul>

<%= link_to "New product", new_product_path, :class=> "btn btn-success" %>

app/views/products/new.html.erb
<% content_for(:title, "New Product | Jungle") %>

<h1>New Product</h1>

<h2>Add a Product</h2>
<%= render('layouts/errors', object: @product) %>
  <%= render('form') %>

<% if @invalid_array != nil %>
  <% @invalid_array.each do |invalid| %>
  <h1><%= invalid.name %></h1>
  <% end %>
<% end %>

<h2>Upload CSV</h2>
 <div class='form-group'>
  <%= form_for @product_upload, url: product_uploads_path, html: { :multipart => true } do |f|%>
    <%= f.label "CSV File" %>
    <%= f.file_field :csv %>
  </div>
    <%= f.submit(:class => "btn btn-success") %>
  <% end %>

app/views/products/show.html.erb
<% content_for(:title, "#{@product.name} | Jungle") %>

<h1> <%= @product.name %> </h1>
  <%= image_tag(@product.picture.url(:medium)) %>
  <ul>
    <li><%= @product.price %></li>
    <li><%= @product.description%></li>
  </ul>
<%= link_to "Product Menu", products_path, :class=> "btn btn-primary" %>
<% if current_user %>
  <%= link_to "Edit Product", edit_product_path, :class=> "btn btn-warning" %>
  <%= link_to "Delete", product_path(@product),
                      :confirm => "You sure?",
                      :method => "delete",
                      :class => "btn btn-danger" %>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :multipart => true } do |f| %>
  <div class='form-group'>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :password %>
    <%= f.text_field :password %>
    <%= f.label :password_confirmation %>
    <%= f.text_field :password_confirmation %>
  </div>
    <%= f.submit(:class => "btn btn-success") %>
<% end %>

app/views/users/edit.html.erb
<% content_for(:title, "#{@user.name} | Edit menu") %>

<h1>Edit Menu </h1>

<%= render('layouts/errors', object: @user) %>
  <%= render('form') %>

app/views/users/index.html.erb
<% content_for(:title, "All Users | Jungle") %>

<h1>Users</h1>

<ul>
  <% @users.each do |user| %>
    <li><%= link_to "#{user.name}", user_path(user) %>
    </li>
  <% end %>
</ul>

<%= link_to "New user", new_user_path, :class=> "btn btn-success" %>

app/views/users/new.html.erb
<% content_for(:title, "New User | Jungle") %>

<h1>New User</h1>

<h2>Add a User</h2>
<%= render('layouts/errors', object: @user) %>
  <%= render('form') %>

app/views/users/show.html.erb
<% content_for(:title, "#{@user.name} | Jungle") %>

<h1> <%= @user.name %> </h1>

<%= link_to "User Menu", users_path, :class=> "btn btn-primary" %>
<%= link_to "Edit User", edit_user_path, :class=> "btn btn-warning" %>
<%= link_to "Delete", user_path(@user),
                      :confirm => "You sure?",
                      :method => "delete",
                      :class => "btn btn-danger" %>